#!/bin/bash
##
# GamePanelX V3
# RedHat/CentOS/Fedora initscript
# chkconfig: 345 55 25
# description: GamePanelX Remote
#
. /etc/rc.d/init.d/functions

case "$1" in
start)
        echo -n "Starting GamePanelX Manager:"

	# Start manager
        /usr/local/gpx/bin/GPXManager

	# Start FTP server
	if [ -f /usr/local/gpx/ftpd/start.sh ]; then
		/usr/local/gpx/ftpd/start.sh
	fi

        echo_success
        echo
        ;;
stop)
        echo -n "Stopping GamePanelX Manager:"

	# Stop manager
	if [ -f /usr/local/gpx/gpxmanager.pid ]; then
		pid_gpxman=$(cat /usr/local/gpx/gpxmanager.pid)

		if [ -e /proc/$pid_gpxman ]; then
			kill $(cat /usr/local/gpx/gpxmanager.pid)
		fi
	fi

	# Stop FTP server
	if [ -f /usr/local/gpx/ftpd/start.sh ]; then
		if [ "$(ps -ef | grep 'pure-ftpd (SERVER)' | grep -v grep)" ]; then
			killall pure-ftpd
		fi
	fi

        echo_success
        echo
        ;;
restart)
        $0 stop
        $0 start
        ;;
*)
        echo "usage: $0 [start|stop|restart|condrestart]"
esac
exit 0
